package utils

import (
	"fmt"

	"github.com/jung-kurt/gofpdf"
)

type CertData struct {
	WorkID     string
	Title      string
	Artist     string
	OwnerName  string
	FileHash   string
	RegisterAt string
	TxID       string
}

func GenerateCertificatePDF(data *CertData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	pdf.SetFont("Arial", "B", 22)
	pdf.CellFormat(0, 16, "Digital Copyright Certificate", "", 1, "C", false, 0, "")
	pdf.Ln(6)

	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(0, 8, "Certificate of Blockchain-based Copyright Registration", "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 8, "This certificate is generated by the Music Copyright Platform", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	addField := func(label, value string) {
		pdf.SetFont("Arial", "B", 11)
		pdf.CellFormat(55, 9, label+":", "", 0, "L", false, 0, "")
		pdf.SetFont("Arial", "", 11)
		pdf.CellFormat(0, 9, value, "", 1, "L", false, 0, "")
	}

	addField("Work ID", data.WorkID)
	addField("Title", data.Title)
	addField("Artist", data.Artist)
	addField("Copyright Owner", data.OwnerName)
	addField("Registration Time", data.RegisterAt)
	pdf.Ln(4)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 9, "File Fingerprint (SHA-256)", "", 1, "L", false, 0, "")
	pdf.SetFont("Courier", "", 9)
	pdf.MultiCell(0, 6, data.FileHash, "", "L", false)
	pdf.Ln(4)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 9, "Fabric Transaction ID", "", 1, "L", false, 0, "")
	pdf.SetFont("Courier", "", 9)
	pdf.MultiCell(0, 6, data.TxID, "", "L", false)
	pdf.Ln(10)

	pdf.SetFont("Arial", "I", 9)
	pdf.CellFormat(0, 8, "This certificate is generated based on Hyperledger Fabric blockchain records.", "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 8, fmt.Sprintf("Verification URL: http://localhost:8080/api/v1/copyright/%s", data.WorkID), "", 1, "C", false, 0, "")

	var buf []byte
	return buf, pdf.Output(&pdfOutput{w: &buf})
}

type pdfOutput struct {
	w *[]byte
}

func (p *pdfOutput) Write(b []byte) (int, error) {
	*p.w = append(*p.w, b...)
	return len(b), nil
}
